DELIMITER //

CREATE PROCEDURE IF NOT EXISTS EGetBooks()
BEGIN
   SELECT * FROM books;
END //

DELIMITER ;

CALL GetBooks;

DROP PROCEDURE IF EXISTS EGetBooks;

SELECT ROUTINE_NAME
FROM information_schema.ROUTINES
WHERE ROUTINE_TYPE = 'PROCEDURE' 
AND ROUTINE_SCHEMA = 'library';
